[package]
name = "wiki-history-game"
version = "0.1.0"
authors = ["Tom Watson <tom@tomjwatson.com>"]
edition = "2018"

[dependencies]
regex = "1.4.5"
reqwest = { version = "0.11.2", features = ["blocking", "json"] }
serde_json = "1.0.64"
urlencoding = "1.1.1"
